### ISSUE TITLE
GraceTabNote font size

### ISSUE THREAD

**Issue by jaredjj3** [vexflow/vexflow#255]
I would like to make grace tab note font smaller than grace notes. There doesn't seem to be a publicly exposed mechanism to do this.

```ts
const vexflowGraceTabNote = new vexflow.GraceTabNote({
  positions: positions,
  duration: graceEntry.durationType,
}).setFontSize(GRACE_TAB_NOTE_FONT_SIZE);
```

<img width="321" alt="Google Chrome 2025-01-13 06 41 21" src="https://github.com/user-attachments/assets/1e656d42-55b5-4b09-855a-0dd6b45ebb50" />

However, I saw that `fretElement` is exposed as `protected`.

```ts
class HackedVexflowGraceTabNote extends vexflow.GraceTabNote {
  setFontSize(size?: string | number): this {
    for (const fretElement of this.fretElement) {
      fretElement.setFontSize(size);
    }
    return this;
  }
}

const vexflowGraceTabNote = new HackedVexflowGraceTabNote({
  positions: positions,
  duration: graceEntry.durationType,
}).setFontSize(GRACE_TAB_NOTE_FONT_SIZE);
```

<img width="361" alt="Google Chrome 2025-01-13 06 39 31" src="https://github.com/user-attachments/assets/0b29012c-13f5-41ba-a22f-0211211a6224" />

This is _almost_ the result I want, except I would like the `GraceTabNotes` vertically centered with respect to the `TabNote` they're attached to.

**Comment by jaredjj3** [comment]
I got the vertical positioning I wanted by updating `renderOptions.yShift`.

```ts
const vexflowGraceTabNote = new HackedVexflowGraceTabNote({
  positions: positions,
  duration: graceEntry.durationType,
}).setFontSize(GRACE_TAB_NOTE_FONT_SIZE);
vexflowGraceTabNote.renderOptions.yShift--
```

<img width="330" alt="image" src="https://github.com/user-attachments/assets/6c80154c-07c0-432e-81fd-6c855f8236dc" />

**Comment by jaredjj3** [comment]
Thanks! `MetricsDefault` isn't exported, so it doesn't seem I can change it: https://github.com/vexflow/vexflow/blob/20f801d1aec367576ee3817586c99c78b61e5f47/src/index.ts#L35

How do I override it?

**Comment by rvilarl** [comment]
you are right, metrics is not exported

**Comment by rvilarl** [comment]
@jaredjj3 this should be fixed in the vexflow 5.0.0-beta.1 Metrics is now exported

**Comment by jaredjj3** [comment]
@rvilarl thanks! I can update the metric, but it doesn't seem to affect anything.

```ts
vexflow.MetricsDefaults.GraceTabNote.fontScale = 1 / 8;

const vexflowGraceTabNote = new vexflow.GraceTabNote({
  positions: positions,
  duration: graceEntry.durationType,
});
vexflowGraceTabNote.renderOptions.yShift--;
```

before, 5.0.0-beta.1, diff, after

![Image](https://github.com/user-attachments/assets/262dab1d-40d4-4d67-b2cd-7e93e331ed03)

My guess is that nothing seems to be using that metric: https://github.com/vexflow/vexflow/blob/0ca6f889545c33cce851b420c24945f6eb685aeb/src/gracetabnote.ts

**Comment by rvilarl** [comment]
@jaredjj3 I have looked into that, there is a cache that has to be cleared to accept the new value. Please try:

```js
vexflow.MetricsDefaults.GraceTabNote.fontScale = 1 / 8;
vexflow.Metrics.clear('GraceTabNote');

const vexflowGraceTabNote = new vexflow.GraceTabNote({
  positions: positions,
  duration: graceEntry.durationType,
});
vexflowGraceTabNote.renderOptions.yShift--;

```

**Comment by jaredjj3** [comment]
> [@jaredjj3](https://github.com/jaredjj3) I have looked into that, there is a cache that has to be cleared to accept the new value. Please try:
> 
> vexflow.MetricsDefaults.GraceTabNote.fontScale = 1 / 8;
> vexflow.Metrics.clear('GraceTabNote');
> 
> const vexflowGraceTabNote = new vexflow.GraceTabNote({
>   positions: positions,
>   duration: graceEntry.durationType,
> });
> vexflowGraceTabNote.renderOptions.yShift--;

Thanks! I'm still getting the same result on 5.0.0 unfortunately. Are you getting a different result?
